# Iris Flowers Classification :

# Predict the different species of flowers on the length of there petals and sepals


In [14]:
#loading the libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
# Loading the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target


In [4]:
# Creating a dataFrame for easier data manipulation
iris_df = pd.DataFrame(data=np.c_[X, y], columns=iris.feature_names + ['species'])
iris_df['species'] = iris_df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})


In [5]:
#Spliting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [6]:
# Creating a RandomForestClassifier 
clf = RandomForestClassifier(n_estimators=100, random_state=42)

In [7]:
# Training the classifier on the training data
clf.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [9]:
# Making predictions on the test data
y_pred = clf.predict(X_test)

In [10]:
# Evaluating the classifier
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, target_names=iris.target_names)


In [12]:
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)
print('Classification Report:')
print(classification_rep)

Accuracy: 1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

